### ISSUE TITLE
provide simple render as a binary

### ISSUE THREAD

**Issue by patrickelectric** [Canop/termimad#31]
It would be nice if the project could have a simple markdown render binary 
E.g: https://github.com/charmbracelet/glow

**Comment by Canop** [comment]
There's one: [clima](https://github.com/Canop/clima).

But I don't make much efforts on it because termimad isn't a general purpose markdown renderer. It's just a facility to improve terminal applications using a markdown based semantic. I'm sure most markdown renderers are better than clima and better than what could be done with just termimad.

**Comment by patrickelectric** [comment]
> There's one: [clima](https://github.com/Canop/clima).
> 
> But I don't make much efforts on it because termimad isn't a general purpose markdown renderer. It's just a facility to improve terminal applications using a markdown based semantic. I'm sure most markdown renderers are better than clima and better than what could be done with just termimad.

I accept recommendations, because everything appears not as good as termimad examples :laughing:

**Comment by Canop** [comment]
TBH I never tested any terminal markdown renderer except the one I fast wrote... I just figured it would be easy to make something better ^^

**Comment by patrickelectric** [comment]
Ook, I'll close the issue so.

**Comment by Canop** [comment]
> Ook, I'll close the issue so.

Yeah. If you think it's worth improving clima, write an issue on that project.
