### ISSUE TITLE
Rendering inline code with newlines

### ISSUE THREAD

**Issue by mkeeter** [Canop/termimad#38]
We've been using `termimad` to print documentation in the [Humility debugger](https://github.com/oxidecomputer/humility/), and it's been great so far (feel free to add it to the list of projects, or I can open a PR to do so).

I noticed that if inline code spans multiple input lines, the highlighting is not maintained.

For example,
```
When listening, it is mandatory to specify the interface (e.g. `humility rpc
--listen -i en0` on MacOS).
```
is printed like this:

![image](https://user-images.githubusercontent.com/745333/208497741-33fb23e5-ab59-4985-adb1-ca6d7124f356.png)

It looks like the code highlighting terminates at the end of the line, instead of continuing to the backtick on the next line.

This is unfortunate, because our docs are written as docstrings, i.e. with hard-wrapping ([here](https://github.com/oxidecomputer/humility/blob/8f53e59bad0b313640f750aecd2fe20808f165f2/cmd/rpc/src/lib.rs#L50-L51)).

Any ideas on how to fix or work around this issue?

Thanks!

**Comment by Canop** [comment]
It's by design that spans don't extend to the following lines. Lines are parsed independently. In my experience spans covering several lines in markdown are more often that not errors and have a tendency to break the whole page.

Now, I think it would be quite easy to have an option in text parsing to allow continuation of italic, code, bold, and strikeout spans.

I'll look into that.

(regarding the mention of Humility in Termimad's readme, yes a PR would be welcome)

**Comment by Canop** [comment]
Version 0.21.0 of Termimad should fix your problem. See the parse-options example.

Waiting for confirmation before closing (or not) this issue.

**Comment by mkeeter** [comment]
Looks great, thanks!
<img width="631" alt="Screenshot 2023-02-06 at 10 24 09 AM" src="https://user-images.githubusercontent.com/745333/217012107-e1a0f220-871f-4c24-a23d-6e1493e152e3.png">

**Comment by Canop** [comment]
Cool. Waiting for your PR, then.
