### ISSUE TITLE
How to render a code block that has new lines in it in one block.

### ISSUE THREAD

**Issue by pythops** [Canop/termimad#43]
When I try to render a piece of code that contains a new line in it, I get the new line without any background highlight.

for instance, 
```
use termimad;

fn main() {
    let code = r#"
        let x =0;

        println!("{}", x);

    "#;

    println!("{}", termimad::MadSkin::default_dark().term_text(code));
}
```
this will produce this rendering
![screenshot-1691873778](https://github.com/Canop/termimad/assets/57548585/d9aabc5f-e1e6-4f56-8d71-20d459f65e92)

as you can see it does not render it in one block.

**Comment by Canop** [comment]
The problem isn't really with termimad. The problem is your middle line is missing the tab or 4 spaces making it a line of codes.

Possible solutions depending on your case:
* build the string another way (rust literals don't allow lines with only spaces, I think, though)
* use a termimad template
* use code fences

With code fences:


    fn main() {
        let code = r#"
    ```
        let x =0;

        println!("{}", x);
    ```
    "#;

        println!("{}", termimad::MadSkin::default_dark().term_text(code));
    }

**Comment by pythops** [comment]
Thanks for the answer. We can mark this as closed then :)
